// Wikipedia Commons images for each episode — public domain medical illustrations
export const EPISODE_TOPIC_IMAGES: Record<string, string> = {
  "01-the-cell":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Typical_human_cell.tif/lossy-page1-813px-Typical_human_cell.tif.jpg",
  "02-birth":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Postpartum_baby2.jpg/960px-Postpartum_baby2.jpg",
  "03-the-body-guards":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Blausen_0909_WhiteBloodCells.png/960px-Blausen_0909_WhiteBloodCells.png",
  "04-bone-marrow":
    "https://upload.wikimedia.org/wikipedia/commons/d/d5/Section_of_bone_marrow_tissue_%28Prussian_blue_stain%29.jpg",
  "05-blood-vessels":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Blood_vessels_%28retouched%29_-en.svg/960px-Blood_vessels_%28retouched%29_-en.svg.png",
  "06-blood-platelets":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Platelets2.JPG/960px-Platelets2.JPG",
  "07-the-heart":
    "https://upload.wikimedia.org/wikipedia/commons/1/1b/Heart_anterior_exterior_view.png",
  "08-breathing":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Respiratory_system_complete_en.svg/960px-Respiratory_system_complete_en.svg.png",
  "09-the-brain":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Blausen_0657_MultipolarNeuron.png/960px-Blausen_0657_MultipolarNeuron.png",
  "10-the-neurons":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Blausen_0657_MultipolarNeuron.png/960px-Blausen_0657_MultipolarNeuron.png",
  "11-the-eye":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Krilleyekils.jpg/960px-Krilleyekils.jpg",
  "12-the-ear":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Human_right_ear_%28cropped%29.jpg/960px-Human_right_ear_%28cropped%29.jpg",
  "13-the-skin":
    "https://upload.wikimedia.org/wikipedia/commons/1/13/Human_skin_structure.jpg",
  "14-mouth-and-teeth":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/06-10-06smile.jpg/960px-06-10-06smile.jpg",
  "15-digestion":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Digestive_system_diagram_en.svg/960px-Digestive_system_diagram_en.svg.png",
  "16-the-liver":
    "https://upload.wikimedia.org/wikipedia/commons/1/15/Anatomy_Abdomen_Tiesworks.jpg",
  "17-the-kidneys":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Blausen_0592_KidneyAnatomy_01.png/960px-Blausen_0592_KidneyAnatomy_01.png",
  "18-the-lymphatic-system":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Blausen_0623_LymphaticSystem_Female.png/960px-Blausen_0623_LymphaticSystem_Female.png",
  "19-bones-and-skeleton":
    "https://upload.wikimedia.org/wikipedia/commons/4/44/Anatomical_Male_Figure_Showing_Heart%2C_Lungs%2C_and_Main_Arteries.jpg",
  "20-muscles-and-fat":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Types_of_muscle.webp/960px-Types_of_muscle.webp.png",
  "21-fight-against-toxins":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Blausen_0592_KidneyAnatomy_01.png/960px-Blausen_0592_KidneyAnatomy_01.png",
  "22-the-immune-system":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Neutrophil_with_anthrax_copy.jpg/960px-Neutrophil_with_anthrax_copy.jpg",
  "23-the-hormones":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Endocrine_English.svg/960px-Endocrine_English.svg.png",
  "24-the-chain-of-life":
    "https://upload.wikimedia.org/wikipedia/commons/8/86/Sperm-egg.jpg",
  "25-repairs":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Wound_Healing_edit.jpg/960px-Wound_Healing_edit.jpg",
  "26-life-goes-on":
    "https://upload.wikimedia.org/wikipedia/commons/5/5a/H._Gray%2C_Anatomy_descriptive_and_surgical_Wellcome_M0016989EA.jpg",
};
